server:
  port: 8083
  servlet:
    context-path: /pedido-service

spring:
  application:
    name: pedido-service

  datasource:
    url: jdbc:postgresql://postgres:5432/pedido_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configurações de exchanges, filas, e listeners do RabbitMQ
rabbitmq:
  pedido:
    cancelado:
      exchange: pedido-cancelado-exchange
      routing-key: pedido-cancelado-routing-key
    created:
      exchange: pedido-created-exchange
      routing-key: pedido-created-routing-key
  exchanges:
    pedido:
      name: pedido.estoque.exchange
      type: direct
    cancelado:
      name: pedido.cancelado.exchange
      type: direct
    pagamento:
      name: pedido.pagamento.exchange
      type: direct
    produto:
      name: produto.atualizado.exchange
      type: direct
  queues:
    pedido:
      created:
        name: pedido.criar.queue
        routing-key: pedido.criar
      cancelado:
        name: pedido.cancelado.queue
        routing-key: pedido.cancelado
    pagamento:
      processar:
        exchange: pagamento.processar.queue
        routing-key: pagamento.processar
    produto:
      atualizado:
        name: produto.atualizado.queue
        routing-key: produto.atualizado
    estoque:
      status:
        name: estoque.status.queue
        routing-key: estoque.status

  listeners:
    # Listeners para o RabbitMQ
    produto-atualizado:
      queue: produto.atualizado.queue
      routing-key: produto.atualizado
      exchange: produto.atualizado.exchange
    pagamento-status:
      queue: pagamento.status.queue
      routing-key: pagamento.status
      exchange: pagamento.status.exchange
    estoque-status:
      queue: estoque.status.queue
      routing-key: estoque.status
      exchange: estoque.status.exchange

mensageria:
  exchange:
    pagamento: pagamento-exchange
  routing-key:
    pagamento: pagamento-routing-key