server:
  port: 8083  # porta do serviço de pedidos (diferente dos outros)
  servlet:
    context-path: /pedido-service

spring:
  application:
    name: pedido-service

  datasource:
    url: jdbc:postgresql://postgres:5432/pedido_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configurações de filas RabbitMQ
mensageria:
  queues:
    criar-pedido: pedido.criar
    atualizar-status: pedido.atualizar.status
